default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: isec_buddy_db
  username: '5uDb8udDy'
  password: 'uMGUdk>9#Yx!5G7N_AzEv}i0'
  #username: <%= ENV.fetch("MYSQL_USER") { user } %>
  #password: <%= ENV.fetch("MYSQL_PASSWORD") { password } %>
  host: 127.0.0.1
  #host: 94.46.175.52
  port: 3306

  

test:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  database: isec_buddy_db
  username: '5uDb8udDy'
  password: 'uMGUdk>9#Yx!5G7N_AzEv}i0'
  #username: <%= ENV.fetch("MYSQL_USER") { user } %>
  #password: <%= ENV.fetch("MYSQL_PASSWORD") { password } %>
  host: 127.0.0.1
  #host: 94.46.175.52
  port: 3306


production:
  <<: *default
  database: isec_buddy_db


mysql:
  adapter: mysql2
  encoding: utf8mb4
  database: isec_buddy_db
  username: '5uDb8udDy'
  password: 'uMGUdk>9#Yx!5G7N_AzEv}i0'
  #username: <%= ENV.fetch("MYSQL_USER") { user } %>
  #password: <%= ENV.fetch("MYSQL_PASSWORD") { password } %>
  host: 127.0.0.1
  #host: 94.46.175.52
  port: 3306