
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: buddy_isec_app_development

test:
  <<: *default
  database: buddy_isec_app_development


production:
  <<: *default
  username: <%= ENV.fetch("MYSQL_USER", "default_username") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "default_password" } %>
  host: 94.46.175.52
  port: 3306


#test:
#  <<: *default
#  username: GoncaloFraDuCat
#  password: Gcatarro97NYK!
#  host: 127.0.0.1
#  port: 3306
#  database: Isec_buddy_db
